export const GENRES = [
    "Pop",
    "Hip Hop",
    "Rap",
    "Rock",
    "R&B",
    "Electronic",
    "Country",
    "Latin",
    "Jazz",
    "Classical",
    "Folk",
    "Blues",
    "Metal",
    "Reggae",
    "Alternative",
    "Indie",
    "Dance",
    "Soul",
    "Punk",
    "Gospel",
    "K-Pop",
    "J-Pop",
    "World",
    "Instrumental",
    "Soundtrack",
    "Spoken Word",
    "Children's Music"
] as const;

export const LANGUAGES = [
    "English",
    "Hindi",
    "Spanish",
    "French",
    "German",
    "Japanese",
    "Korean",
    "Chinese (Mandarin)",
    "Russian",
    "Portuguese",
    "Italian",
    "Arabic",
    "Bengali",
    "Punjabi",
    "Tamil",
    "Telugu",
    "Malayalam",
    "Kannada",
    "Marathi",
    "Gujarati",
    "Urdu",
    "Bhojpuri"
] as const;

export const VERSION_TYPES = [
    "Original",
    "Cover",
    "Remix",
    "Live",
    "Instrumental",
    "Radio Edit",
    "Extended Mix",
    "Acoustic",
    "Demo"
] as const;
